sudo: false
language: c

cache:
  directories:
    - $HOME/.stack

env:
  global:
    - NODEVER=4

addons:
  apt:
    packages: &packages
      - libnetcdf-dev
      - netcdf-bin
      - libpq-dev
  postgresql: &postgresql "9.4"

services:
- postgresql

matrix:
  include:
    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.3 ALEXVER=3.1.7 HAPPYVER=1.19.5
      compiler: ": #cabal"
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - *packages
            - cabal-install-1.22
            - ghc-7.10.3
            - alex-3.1.7
            - happy-1.19.5
        postgresql: *postgresql
    - env: BUILD=stack
      compiler: ": #stack"
      addons:
        apt:
          packages:
            - *packages
            - libgmp
            - libgmp-dev
        postgresql: *postgresql

before_install:
  - unset CC
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH

  - mkdir -p $HOME/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'

  - rm -rf $HOME/.nvm
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - . $NVM_DIR/nvm.sh
  - nvm install $NODEVER
  - nvm use $NODEVER
  - travis_retry npm install -g bower grunt-cli

install:
  - |
    set -ex
    case "$BUILD" in
      cabal)
        travis_retry cabal update
        travis_retry cabal install Cabal-1.22.4.0
        travis_retry cabal install --jobs --only-dependencies --enable-tests --reorder-goals
        ;;
      stack)
        stack --no-terminal --install-ghc test --only-dependencies
        ;;
    esac
    set +ex

before_script:
  - createdb volare_test
  - echo "CREATE USER volare WITH ENCRYPTED PASSWORD 'password'" | psql -U postgres

script:
  - |
    set -ex
    case "$BUILD" in
      cabal)
        cabal configure --enable-tests -fglibcxx && cabal build && cabal test
        ;;
      stack)
        stack --no-terminal test --flag volare:glibcxx
        ;;
    esac
    set +ex
