host: "_env:HOST:*4"
port: "_env:PORT:3000"

database:
  user: "_env:PGUSER:volare"
  password: "_env:PGPASS:password"
  host: "_env:PGHOST:localhost"
  port: "_env:PGPORT:5432"
  database: "_env:PGDATABASE:volare"
  poolsize: "_env:PGPOOLSIZE:10"

google-api-key: "_env:GOOGLE_API_KEY:<specify your google api key>"
